### ISSUE TITLE
pypyjs-source

### ISSUE THREAD

**Issue by jedie** [pypyjs/pypyjs#136]
(Sorry, this is more a forum thread than a issues :) )

I have made two new, experimental repositories:

* https://github.com/jedie/pypyjs-source

This contains the latest release from https://github.com/rfk/pypyjs/releases/download/ and only one minimal example file.

This repro can be used via git submodule to create a own PyPy.js page.
So you can easy include the needed source files without to blow up the git repository ;)
This is maybe also helpful, if there is a CDN, to host the files on own server...

As a example, to to use https://github.com/jedie/pypyjs-source i made:

* https://github.com/jedie/pypyjs-examples

Both pages used GitHub Pages, e.g.:

* https://jedie.github.io/pypyjs-source/
* https://jedie.github.io/pypyjs-examples/mandelbrot.html
* https://jedie.github.io/pypyjs-examples/mandelbrot-nojit.html
* https://jedie.github.io/pypyjs-examples/minimal_console.html

This examples aimed to use only a few external dependencies.

(EDIT: Cross-post: http://www.python-forum.org/viewtopic.php?f=10&t=15769&p=30247#p30247 )

**Comment by rfk** [comment]
I made two new repos in the pypyjs github org:

  * https://github.com/pypyjs/pypyjs-release
  * https://github.com/pypyjs/pypyjs-release-nojit

The plan is to have each contain the contents of the release build, as a handy bit submodule.  The `master` branch of each will track the latest release, and we can make a new tag on the repo for each subsequent release, so that it's easy to pin a submodule checkout to a specific release.

It probably makes sense to tweak the readme, add an example page, etc.  We should do that in the release bundle though so that folks who download it directly will get the same affordances.

**Comment by rfk** [comment]
Closing this, let's iterate in the new repos
