### ISSUE TITLE
pypyjs / PyPyJS / PyPy-JS / PyPy.js ...

### ISSUE THREAD

**Issue by jedie** [pypyjs/pypyjs#147]
I know, a kind of a nonsense question...

What's the "official" spelling ???

Every time I write pypy, i have to think about the right spelling ;)

**Comment by crantila** [comment]
This actually seems like an important question. And there's a related question, in my mind, about the naming conflict between the project overall and the "pypy.js" library it contains... which seems incidental the file that's the point of the project overall, which is "pypy-vm.js"?

As this project continues to evolve (see what I did there?) someone ought to choose these names deliberately!

**Comment by jedie** [comment]
The github org name is **pypyjs** -> https://github.com/pypyjs/
The main repro called **pypyjs** -> https://github.com/pypyjs/pypyjs/

So what's about to rename all variants to pypyjs ?
On the other side: this low-case variant will be not good noticed in normal continuous text...

**Comment by kirbyfan64** [comment]
All the repository descriptions (and the organization description) use PyPy.js.

**Comment by rfk** [comment]
I played around with a few variants when naming things originally and I think I prefer "PyPy.js" as the canonical name for the project.  But I'm open to arguments that it should be something else :-)

Perhaps we can standardize on "PyPy.js" when appearing in text, and "pypyjs" as the name of things in code contexts where dots are not welcome?

> And there's a related question about the naming conflict between the project overall and
> the "pypy.js" library it contains

@crantila I'd like to hear more about this.  I agree that the `vm.js` file is the real heart of the project, but the `pypy.js` file is the entry-point that you actually load in order to use things.

**Comment by crantila** [comment]
> Perhaps we can standardize on "PyPy.js" when appearing in text, and "pypyjs" as the name of things in code contexts where dots are not welcome?

+1

----

Regarding the naming conflict I mentioned above, it first occurred to me while explaining PyPy.js to collaborators on my project. (We've yet to contribute to PyPy.js directly, but it will happen!) The confusion arises because there seem to be three things called PyPy.js: the project, the JavaScript library, and the interpreter.

The problem is most noticeable when someone's first trying to wrap their head around the nature of running Python in JavaScript. People want to understand who does what, where, and why. Saying "this happens in PyPy.js" is ambiuguous in many cases. Depending on what's being explained at the moment it can either mean "this happens in PyPy.js the JavaScript library instead of the interpreter," or "this happens in PyPy.js the interpreter instead of the JavaScript interpreter," or even other things.

To some extent, newcomers may simply be confused about what's going on because it's different and new. Yet we (PyPy.js contributors) can alleviate this confusion by communicating as clearly as possible. The most obvious solution is to provide additional clarification in documentation whenever "PyPy.js" might be ambiguous, but I feel this may prove to be unnecessarily difficult over time. A simpler, one-time solution would rename something to avoid troublesome ambiguity altogether.

My suggestion is therefore to rename ``pypy.js``, the JavaScript file that is the entry-point to the PyPy.js interpreter, to ``pypy-bridge.js``. I've already started calling this file "the JavaScript bridge" because the metaphor of bridging between Python-land and JavaScript-land is quite helpful. The remaining ambiguity between PyPy.js as a project and PyPy.js the interpreter seems unlikely to cause troublesome ambiguity.

What does everyone think? There may be even better solutions out there!

**Comment by jedie** [comment]
My 2ct:

**PyPy.js** as project name:
* pro:
  * looks nice
  * described the project IMHO very good
* con:
  * looks like a filename
  * can't be used in sources, because of the dot and case sensitive

**pypyjs** as the name for everything:
* pro:
  * can be used consistently, everywhere
  * github group and git repro use it already
  * all low case
* con:
  * Looks not so nice than "PyPy.js"
 

About renaming ```pypy.js```: 

What's about to rename it to ```pypyjs-init.js``` ?
I think ```bridge``` doesn't match it completely.

btw. we have three important files...
From the https://github.com/pypyjs/pypyjs-release/blob/master/lib/README.txt : 

  * ```pypy.js```:         public-facing API to the PyPy VM
  * ```pypy.vm.js```:      the PyPy VM itself, as built by rpython+emscripten
  * ```pypy.vm.js.mem```:  memory initializer data for the PyPy VM

So what's renaming all three (If ```pypy.js``` will be renamed) ?
e.g.:

* ```pypyjs-init.js```
* ```pypyjs-vm.js```
* ```pypyjs-mem.dat```

The file extension ```.dat``` is a other question, see: https://github.com/pypyjs/pypyjs.github.io/issues/4

**Comment by rfk** [comment]
@crantila thanks for expanding on that, I see you points.  There's also some additional weirdness around the naming of the release bundles, their directory structure, etc.  @jedie, your list of pros and cons closely matches my own :-)

Would it be too much repetition of "js" if we were to name files like this?

```
  pypyjs.js
  pypyjs.vm.js
  pypyjs.vm.js.mem
```

**Comment by crantila** [comment]
I think that would be a big improvement, but perhaps still not as clear as marking the JavaScript file with "init" or "bridge" or similar.

**Comment by jedie** [comment]
> ...marking the JavaScript file with "init" or "bridge" or similar.

:+1:

**Comment by rfk** [comment]
> marking the JavaScript file with "init" or "bridge" or similar.

I gotta be honest, I vaguely dislike this but I can't articulate the reasons why.  Perhaps I just need to sleep on it :-)

Would calling the helper file something other than "vm" help to clear things up?

**Comment by jedie** [comment]
any news here?

**Comment by rfk** [comment]
Sorry, I'm travelling for work at the moment so trying to stay on top of these issues in-between meetings etc.  I think I still like the scheme from https://github.com/pypyjs/pypyjs/issues/147#issuecomment-114548127 the best of all the options considered, will try it out for the next release.

Do you think the top-level name exposed by the javascript should change from `PyPyJS` to `pypyjs` for consistency?
